CONTIKI = /home/user/contiki-2.7

CONTIKI_PROJECT = saamrp-node saamrp-sink
all: $(CONTIKI_PROJECT)

CONTIKI_WITH_IPV6 = 1

UIP_CONF_IPV6=1
UIP_CONF_DS6_ROUTING=1

include $(CONTIKI)/Makefile.include

